name = "ai-music"
compatibility_date = "2025-11-26"

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_NAME = "AI音乐"

[[d1_databases]]
binding = "AIMUSIC_DB"
database_name = "ai_music_db"
database_id = "local"

[[kv_namespaces]]
binding = "AIMUSIC_KV"
id = "local"

[[r2_buckets]]
binding = "AIMUSIC_MEDIA"
bucket_name = "ai-music-media"
