name = "ai-music"
compatibility_date = "2025-11-26"

pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_NAME = "AI音乐"

[observability]
enabled = true

compatibility_flags = ["nodejs_compat"]